config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :kittens

  root to: "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates_presence_of :name
  validates_presence_of :age
  validates_presence_of :cuteness
  validates_presence_of :softness
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController

  def index
    @kittens = Kitten.all.order(:created_at => "DESC")

    respond_to do |format|
      format.html #{ render :html => @kittens }
      format.json { render :json => @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html #{ render :html => @kitten }
      format.json { render :json => @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def create
    @kitten = Kitten.create(kitten_params)

    @kitten.name.capitalize!
    @kitten.cuteness.capitalize!
    @kitten.softness.capitalize!

    if @kitten.save
      flash[:notice] = "Kitten successfully created"
      redirect_to @kitten
    else
      flash[:alert] = "Something went wrong, please check your input"
      render :new
    end
  end

  def update
    @kitten = Kitten.find(params[:id])
    @kitten.update(kitten_params)

    if @kitten.save
      flash[:notice] = "Kitten successfully updated"
      redirect_to kitten_path
    else
      flash[:alert] = "Something went wrong, please check your input"
      render :edit
    end
  end


  def destroy
    @kitten = Kitten.find(params[:id])

    if @kitten.destroy
      flash[:notice] = "'#{@kitten.name}' successfully deleted."
      redirect_to @kitten
    else
      flash[:alert] = "Unable to delete '#{@kitten.name}'"
      render :show
    end
  end




  private
  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= simple_form_for @kitten do |form| %>
<div class="form field">
  <%= form.input :name, wrapper: false, input_html: {class:"input", autofocus: true }, label_html: {class: "label"} %>
<div>

<div class="form field">
  <%= form.input :age, wrapper: false, input_html: {class:"input"}, label_html: {class:"label"} %>
</div>

<div class="form field">
  <%= form.input :cuteness, wrapper: false, input_html: {class:"input"}, label_html: {class:"label"} %>
</div>

<div class="form field">
  <%= form.input :softness, wrapper: false, input_html: {class:"input"}, label_html: {class:"label"} %>
</div>

  <div class="field">
    <div class="field-control">
      <%= form.submit "Submit", class:"button is-info" %>
    </div>
  <div>
<% end %>

app/views/kittens/edit.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-4">

        <h1 class="title is-4"> Edit Kitten </h1>

        <%= render "form" %>
        <br />
        <%= link_to "Delete", kitten_path(@kitten), method: :delete, data: { confirm: "Are you sure"}, class: "button is-danger" %>
        <%= link_to "Back", root_path, class:"button is-info" %>


      <div>
    </div>
  </div>
</div>

app/views/kittens/index.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-4">

        <h1 class="title is-4"> All Kittens (<%=@kittens.count %>)  <%= link_to "Creat New Kitten", new_kitten_path, class: "button is-info" %></h1>



        <% @kittens.each do |kitten| %>
          <table border="2">
            <tr>
              <th>Name</th>
              <th>Age</th>
              <th>Cuteness</th>
              <th>Softness</th>
            <tr>
            <tr>
              <td><%= kitten.name %></td>
              <td><%= kitten.age %></td>
              <td><%= kitten.cuteness %></td>
              <td><%= kitten.softness %></td>
            </tr><hr />
          </table>
          <%= link_to "edit", edit_kitten_path(kitten[:id]) %>
          <%= link_to "show", kitten_path(kitten[:id]) %>

        <% end %><br /><hr />

      <div>
    </div>
  </div>
</div>

app/views/kittens/new.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-4">

        <h1 class="title is-4"> New Kitten </h1>

        <%= render "form" %>
        <br />
        <%= link_to "Back to all kittens", kittens_path(@kittens), class: "button is-primary" %>

      <div>
    </div>
  </div>
</div>

app/views/kittens/show.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-4">

        <h1 class="title is-4"> Your Kitten </h1>

        <div>
          <strong> Name: </strong>
          <%= @kitten.name %><br />
          <strong> Age: </strong>
          <%= @kitten.age %><br />
          <strong> Cuteness: </strong>
          <%= @kitten.cuteness %><br />
          <strong> Sofness: </strong>
          <%= @kitten.softness %><br />

          <%= link_to "Edit", edit_kitten_path(@kitten[:id]), class: "button is-info" %>
          <%= link_to "Delete", kitten_path(@kitten[:id]), method: :delete, data: {confirm: "Are you sure"}, class:"button is-danger" %>
          <%= link_to "Back", root_path, class: "button is-info" %>
        <div>

      <div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"> <%= notice %> </p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"> <%= alert %> </p>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>